### ISSUE TITLE
Windows originating from the different parent windows are not getting docked

### ISSUE THREAD

**Issue by sukhminderxx** [openfin/snap-and-dock#30] opened 2018-03-28 06:48 UTC
Hi

I am using the dockingManager class. The windows that are created from the same parent window are dockable. But if the windows originate from different parent windows ( which has same parent application ), then they cannot be docked.
Please let me know what did I miss.
Thanks.

**Comment by algreasley** [comment] 2018-04-04 19:29
At a guess, you may have 2 DockingManager instances in play.
If you could post a few more details, or perhaps debug the DM class to track registration, I can help you further.

**Comment by sukhminderxx** [comment] 2018-04-17 08:44
Hi
Thanks for replying. I have to create the openfin windows through different services. Hence, to eliminate the multiple instances, I modified the DM class to return a single instance like this:

DM.js:
let dockingManager = new DockingManager();
export default dockingManager;

On debugging, if I create a window from one service and then I debug on create second window from a different service, I get the this.windows array to be of length 0
_dockingWindow.onLeaveGroup = this.undockWindow;
this.windows.push(dockingWindow);_
This is what confuses me. The same instance is returned from the DM class, still this.windows length comes out to be zero; causing this problem.

Thanks.

**Comment by algreasley** [comment] 2018-04-17 21:55
hi, no problem .. have some more questions for you:

- When debugging, have you stepped through both registrations in the same devtools window?
- Regarding "I have to create the openfin windows through different services" .. in what module / window is each service running, and where in the system is the dockingManager.register(openfinWindow) called?
Problem with singletons is .. you can easily have several of them :)  .. one of the reasons I dropped the getInstance() - perhaps log the creation of the DM
- Also, it might be helpful to know how many windows / javascript VMs are in play in your project?

**Comment by sukhminderxx** [comment] 2018-04-18 11:25
Hi

Please view the explanation below:

- **When debugging, have you stepped through both registrations in the same devtools window?**
_The devtools window was different; because the parent windows (of the windows that I want to dock) are different_
- Regarding "I have to create the openfin windows through different services" .. in what module / window is each service running, and where in the system is the dockingManager.register(openfinWindow) called?
_I am using reactjs and the app has multiple windows. So, each window is a different component; te component accesses its own service and that service imports the dockingManager instance from DM.js_
- **Problem with singletons is .. you can easily have several of them :) .. one of the reasons I dropped the getInstance() - perhaps log the creation of the DM**

- **Also, it might be helpful to know how many windows / javascript VMs are in play in your project?**
_there are multiple windows to be used, and they can originate from divergent parent windows_


Thanks.

**Comment by algreasley** [comment] 2018-04-20 22:34
ok, if you are stepping through .register() in different windows/devtools then I am certain that you are dealing with two (or more) instances of DockingManager.

this library was designed to operate with a single instance of the DockingManager - you can achieve registration of windows in any javascript vm across your application by communicating the new window name to the primary instance (window) which normally hosts the DM - you can use the InterApplicationBus to do this .. see Docking.js for some inspiration - I don't have the java sample running locally, but take a look at
  https://github.com/openfin/snap-and-dock/blob/master/Docking.js#L104
where the separate java application is registering a window (although, note that at present this is a simple example and the lib will not ensure uniqueness of window names across OpenFin applications)

**Comment by sukhminderxx** [comment] 2018-04-24 11:37
Hi,

I added the logic to subscribe to an event in my app window. When that event is caught, the docking is subscribed. On every window creation, that event is published using the interapplicationbus.

It worked perfectly and unabridged.

Thanks for the help. :smile:

**Comment by algreasley** [comment] 2018-04-24 14:56
no worries 😄 

.. closing this issue then.

**Closed** 2018-04-24 14:59 UTC
